from src.models.model_to_model.athlete_sport.model import AthleteSportModel
from src.models.model_to_model.athlete_competition.model import AthleteCompetitionModel
from src.models.model_to_model.judge_competition.model import JudgeCompetitionModel
from src.models.athlete.model import AthleteModel
from src.models.sport.model import SportModel
from src.models.judge.model import JudgeModel
from src.models.stadium.model import StadiumModel
from src.models.competition.model import CompetitionModel
from src.models.trainer.model import TrainerModel
